name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run one line script
        run: echo Hello World Emir !!!
